name: llorona_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  custom_splash: ^0.0.2
  cupertino_icons: ^0.1.3
  meta: ^1.1.8
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.3+1
  chopper: ^3.0.3
  provider: ^4.3.1
  flutter_bloc: ^6.0.1
  rxdart: ^0.24.1
  slide_popup_dialog: ^0.0.2
  flutter_html: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.10.0
  freezed: ^0.11.2
  json_serializable: ^3.3.0
  chopper_generator: ^3.0.5

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/logo_with_title.png
    - assets/icons/search.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat-Black
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Black.ttf
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    - family: Montserrat-ExtraLight
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-ExtraLight.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Light.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Medium.ttf
    - family: Montserrat-Regular
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-SemiBold.ttf
    - family: Montserrat-Thin
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Thin.ttf
        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
